- name: create app user
  user:
    name=budgeteer-landing
    groups=wheel
    append=yes
- name: add ssh key to user
  authorized_key: >-
    user=budgeteer-landing
    key="{{ lookup('file', '~/.ssh/budgeteer-landing.pub') }}"
    state=present
- name: start firewalld
  service: >-
    name=firewalld
    enabled=yes
    state=started
- name: allow firewalld services
  firewalld: >-
    service="{{ item }}"
    permanent=true
    state=enabled
    immediate=yes
  with_items:
    - http
    - https
    - ssh
- name: Setup NTP
  command: timedatectl set-timezone UTC
- yum: >-
    name=ntp
    state=present
- service: >-
    name=ntpd
    enabled=yes
    state=started
- name: Setup EPEL
  yum: >-
    name=epel-release
    state=present
- name: Install nginx
  yum: >-
    name=nginx
    state=present
- name: Start/enable nginx
  service: >-
    name=nginx
    enabled=yes
    state=started
