- name: install pm2
  npm: >-
    name=pm2
    global=yes
    state=present
  become: true
- name: upload nginx config
  copy: src=budgeteer-landing.nginx.conf dest=/etc/nginx/conf.d/budgeteer-landing.conf
  become: true
- name: restart nginx
  service: >-
    name=nginx
    state=restarted
  become: true
- name: upload .env file
  copy: src=dotenv dest=~/.env
