- name: ensure droplet exists
  digital_ocean: >-
    state=present
    command=droplet
    name=budgeteer-landing-1
    unique_name=yes
    size_id=1gb
    region_id=NYC2
    image_id=centos-7-2-x64
    wait=yes
    api_token={{ do_token }}
  register: droplet
- debug: msg="IP is {{ droplet.droplet.ip_address }}"
- name: add droplet to inventory
  add_host: name={{ droplet.droplet.ip_address }} group=droplets

