- name: create app user
  user:
    name=budgeteer-landing
    groups=wheel
    append=yes
- name: add ssh key to user
  authorized_key: >-
    user=budgeteer-landing
    key="{{ lookup('file', '~/.ssh/budgeteer-landing.pub') }}"
    state=present
- name: disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh
- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh
- name: no password for wheel users
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

