---
- hosts: digitalocean
  roles:
    - droplet
  vars:
    do_token: "{{ lookup('credstash', 'digital_ocean_api_key', region='us-east-1') }}"
- hosts: droplets
  roles:
    - web_server
    - node_server


