- hosts: digitalocean
  roles:
    - droplet_prereqs
    - droplet
  tags:
    - frontend
    - backend
- hosts: droplets
  vars:
    ansible_user: budgeteer-landing
  roles:
    - role: deploy_assets
      delegate_to: 127.0.0.1
      tags:
        - frontend
    - role: deploy_app
      tags:
        - backend

